.catalog:
  name: "redash"
  version: "0.1.0"
  description: "redash v3.0.0.b3134"
  uuid: "redash-3.0.0-rancher"
  minimum_rancher_version: "v1.6.0"
  questions:
    - variable: REDASH_HOST_LABEL
      label: "Host with Label to put redash on"
      description: |
        Host label to use as redash 'value' tag.
        ex)'redash=true'
      required: false
      default: ""
      type: "string"
    - variable: "USE_HTTP_PROXY"
      label: "Use HTTP_PROXY?"
      required: true
      default: false
      type: boolean
    - variable: "ADD_PG_CONTAINER"
      label: "Add PostgreSQL Container?"
      required: true
      default: true
      type: boolean
    - variable: "ADD_SAMPLE_DATASET"
      label: "Add Sample DataSet?"
      required: true
      default: true
      type: boolean
    - variable: "INIT_REDASH_DB"
      label: "Initialize the database"
      required: true
      default: false
      type: boolean

    - variable: "MY_TIMEZONE"
      label: "TimeZone"
      description: "Specify Timezone(default JST-9)"
      required: false
      type: "string"
      default: "JST-9"

    - variable: "HTTP_PROXY"
      label: "HTTP_PROXY"
      description: "HTTP_PROXY"
      required: false
      type: "string"
      default: "http://xx.xx.xx.xx:9999"
    - variable: "HTTPS_PROXY"
      label: "HTTPS_PROXY"
      description: "HTTPS_PROXY"
      required: false
      type: "string"
      default: "http://xx.xx.xx.xx:9999"
    - variable: "NO_PROXY"
      label: "NO_PROXY"
      description: "NO_PROXY"
      required: false
      type: "string"
      default: "local,127.0.0.1"

    - variable: "REDASH_HOST_PORT"
      label: "REDASH_HOST_PORT"
      description: "Redash Server Port"
      required: true
      type: "int"
      default: "5000"

    - variable: "REDASH_STATSD_HOST"
      label: "REDASH_STATSD_HOST"
      description: "Host name of StatsD of Graphite Client"
      required: false
      type: "string"
      default: "127.0.0.1"
    - variable: "REDASH_STATSD_PORT"
      label: "REDASH_STATSD_PORT"
      description: "REDASH_STATSD_PORT"
      required: false
      type: "int"
      default: "8125"
    - variable: "REDASH_STATSD_PREFIX"
      label: "REDASH_STATSD_PREFIX"
      description: "REDASH_STATSD_PREFIX"
      required: false
      type: "string"
      default: "redash"

    - variable: "REDASH_HOST"
      label: "REDASH_HOST"
      description: "ex) https://app.redash.io/name"
      required: true
      type: "string"
      default: "127.0.0.1"
    - variable: "REDAH_HTTP_PORT"
      description: "public port to access redash site"
      label: "Public Port"
      required: true
      default: 8180
      type: "int"

    - variable: "REDASH_DATE_FORMAT"
      label: "REDASH_DATE_FORMAT"
      description: "REDASH_DATE_FORMAT"
      required: false
      type: "string"
      default: "YY/MM/DD"
    - variable: "REDASH_ALLOW_SCRIPTS_IN_USER_INPUT"
      label: "REDASH_ALLOW_SCRIPTS_IN_USER_INPUT"
      description: "disable sanitization of text input, allowing full HTML"
      required: false
      type: "string"
      default: "false"
    - variable: "ALLOW_PARAMETERS_IN_EMBEDS"
      label: "ALLOW_PARAMETERS_IN_EMBEDS"
      description: "With this option enabled, Redash reads query parameters from the request URL (risk of SQL injection!)"
      required: false
      type: "string"
      default: "false"
    - variable: "REDASH_LOG_STDOUT"
      label: "REDASH_LOG_STDOUT"
      description: "REDASH_LOG_STDOUT"
      required: false
      type: "string"
      default: "false"

    - variable: "REDASH_MAIL_SERVER"
      label: "REDASH_MAIL_SERVER"
      description: "REDASH_MAIL_SERVER"
      required: false
      type: "string"
      default: "localhost"
    - variable: "REDASH_MAIL_PORT"
      description: "REDASH_MAIL_PORT"
      label: "REDASH_MAIL_PORT"
      required: true
      default: 25
      type: "int"
    - variable: "REDASH_MAIL_USE_TLS"
      label: "REDASH_MAIL_USE_TLS"
      description: "REDASH_MAIL_USE_TLS"
      required: false
      type: "string"
      default: "false"
    - variable: "REDASH_MAIL_USE_SSL"
      label: "REDASH_MAIL_USE_SSL"
      description: "REDASH_MAIL_USE_SSL"
      required: false
      type: "string"
      default: "false"
    - variable: "REDASH_MAIL_USE_SSL"
      label: "REDASH_MAIL_USE_SSL"
      description: "REDASH_MAIL_USE_SSL"
      required: false
      type: "string"
      default: "false"
    - variable: "REDASH_MAIL_USERNAME"
      label: "REDASH_MAIL_USERNAME"
      description: "REDASH_MAIL_USERNAME"
      required: false
      type: "string"
      default: ""
    - variable: "REDASH_MAIL_PASSWORD"
      label: "REDASH_MAIL_PASSWORD"
      description: "REDASH_MAIL_PASSWORD"
      required: false
      type: "string"
      default: ""
    - variable: "REDASH_MAIL_DEFAULT_SENDER"
      label: "REDASH_MAIL_DEFAULT_SENDER"
      description: "REDASH_MAIL_DEFAULT_SENDER"
      required: false
      type: "string"
      default: ""
    - variable: "REDASH_MAIL_ASCII_ATTACHMENTS"
      label: "REDASH_MAIL_ASCII_ATTACHMENTS"
      description: "REDASH_MAIL_ASCII_ATTACHMENTS"
      required: false
      type: "string"
      default: "false"

    - variable: "REDASH_COOKIE_SECRET"
      label: "redash cookies secret"
      description: "Cookie"
      required: true
      type: "string"
      default: "veryveryveryveryverysecret"

    - variable: "REDASH_DB_HOST"
      label: "redash DB Host"
      description: "redash DB Host Name"
      required: true
      type: "string"
      default: "redashdb"
    - variable: "REDASH_DB_USER"
      label: "redash DB user"
      description: "redash DB user"
      required: true
      type: "string"
      default: "postgres"
    - variable: "REDASH_DB_PW"
      label: "redash DB Password"
      description: "redash DB Password"
      required: true
      type: "string"
      default: "pass0000"
    - variable: "REDASH_DB_NAME"
      label: "redash DB name"
      description: "redash DB name"
      required: true
      type: "string"
      default: "postgres"

    - variable: "REDASH_IMAGE_VERSION"
      label: "redash container image Version"
      description: "Specify a version of the redash container to pull (default will pull 3.0.0.b3134)."
      required: true
      type: "string"
      default: "3.0.0.b3134"

    - variable: "PGADMIN_DEF_EMAIL"
      label: "pgAdmin4 user name"
      description: "pgAdmin4 user name(e-mail)"
      required: true
      type: "string"
      default: "admin@hoge.com"
    - variable: "PGADMIN_DEF_PW"
      label: "pgAdmin4 user password"
      description: "pgAdmin4 user password"
      required: true
      type: "string"
      default: "pass0000"
    - variable: "PGADMIN_HTTP_PORT"
      description: "public port to access pgAdmin4 site"
      label: "Public Port"
      required: true
      default: 8280
      type: "int"

    - variable: "VOLUME_DRIVER"
      description:
       For PostgreSQL Volume driver to use with this service.
      label: "Volume driver"
      required: false
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
